spring.application.name=barbearia_kawamura

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_pet
spring.datasource.username=root
spring.datasource.password=escola

spring.jpa.hibernate.ddl-auto=update	

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
